// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_general.proto

#ifndef PROTOBUF_INCLUDED_protobuf_5fgeneral_2eproto
#define PROTOBUF_INCLUDED_protobuf_5fgeneral_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protobuf_5fgeneral_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_protobuf_5fgeneral_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_protobuf_5fgeneral_2eproto();
namespace tutorial {
class proto_general;
class proto_generalDefaultTypeInternal;
extern proto_generalDefaultTypeInternal _proto_general_default_instance_;
class proto_metadata;
class proto_metadataDefaultTypeInternal;
extern proto_metadataDefaultTypeInternal _proto_metadata_default_instance_;
}  // namespace tutorial
namespace google {
namespace protobuf {
template<> ::tutorial::proto_general* Arena::CreateMaybeMessage<::tutorial::proto_general>(Arena*);
template<> ::tutorial::proto_metadata* Arena::CreateMaybeMessage<::tutorial::proto_metadata>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tutorial {

// ===================================================================

class proto_metadata :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tutorial.proto_metadata) */ {
 public:
  proto_metadata();
  virtual ~proto_metadata();

  proto_metadata(const proto_metadata& from);

  inline proto_metadata& operator=(const proto_metadata& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  proto_metadata(proto_metadata&& from) noexcept
    : proto_metadata() {
    *this = ::std::move(from);
  }

  inline proto_metadata& operator=(proto_metadata&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const proto_metadata& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const proto_metadata* internal_default_instance() {
    return reinterpret_cast<const proto_metadata*>(
               &_proto_metadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(proto_metadata* other);
  friend void swap(proto_metadata& a, proto_metadata& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline proto_metadata* New() const final {
    return CreateMaybeMessage<proto_metadata>(nullptr);
  }

  proto_metadata* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<proto_metadata>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const proto_metadata& from);
  void MergeFrom(const proto_metadata& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(proto_metadata* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string checksum = 1;
  void clear_checksum();
  static const int kChecksumFieldNumber = 1;
  const ::std::string& checksum() const;
  void set_checksum(const ::std::string& value);
  #if LANG_CXX11
  void set_checksum(::std::string&& value);
  #endif
  void set_checksum(const char* value);
  void set_checksum(const char* value, size_t size);
  ::std::string* mutable_checksum();
  ::std::string* release_checksum();
  void set_allocated_checksum(::std::string* checksum);

  // @@protoc_insertion_point(class_scope:tutorial.proto_metadata)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr checksum_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protobuf_5fgeneral_2eproto;
};
// -------------------------------------------------------------------

class proto_general :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tutorial.proto_general) */ {
 public:
  proto_general();
  virtual ~proto_general();

  proto_general(const proto_general& from);

  inline proto_general& operator=(const proto_general& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  proto_general(proto_general&& from) noexcept
    : proto_general() {
    *this = ::std::move(from);
  }

  inline proto_general& operator=(proto_general&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const proto_general& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const proto_general* internal_default_instance() {
    return reinterpret_cast<const proto_general*>(
               &_proto_general_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(proto_general* other);
  friend void swap(proto_general& a, proto_general& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline proto_general* New() const final {
    return CreateMaybeMessage<proto_general>(nullptr);
  }

  proto_general* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<proto_general>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const proto_general& from);
  void MergeFrom(const proto_general& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(proto_general* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .tutorial.proto_metadata meta = 1;
  bool has_meta() const;
  void clear_meta();
  static const int kMetaFieldNumber = 1;
  const ::tutorial::proto_metadata& meta() const;
  ::tutorial::proto_metadata* release_meta();
  ::tutorial::proto_metadata* mutable_meta();
  void set_allocated_meta(::tutorial::proto_metadata* meta);

  // .google.protobuf.Any msg = 10;
  bool has_msg() const;
  void clear_msg();
  static const int kMsgFieldNumber = 10;
  const ::google::protobuf::Any& msg() const;
  ::google::protobuf::Any* release_msg();
  ::google::protobuf::Any* mutable_msg();
  void set_allocated_msg(::google::protobuf::Any* msg);

  // bool compressed = 2;
  void clear_compressed();
  static const int kCompressedFieldNumber = 2;
  bool compressed() const;
  void set_compressed(bool value);

  // @@protoc_insertion_point(class_scope:tutorial.proto_general)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::tutorial::proto_metadata* meta_;
  ::google::protobuf::Any* msg_;
  bool compressed_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_protobuf_5fgeneral_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// proto_metadata

// string checksum = 1;
inline void proto_metadata::clear_checksum() {
  checksum_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& proto_metadata::checksum() const {
  // @@protoc_insertion_point(field_get:tutorial.proto_metadata.checksum)
  return checksum_.GetNoArena();
}
inline void proto_metadata::set_checksum(const ::std::string& value) {
  
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tutorial.proto_metadata.checksum)
}
#if LANG_CXX11
inline void proto_metadata::set_checksum(::std::string&& value) {
  
  checksum_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tutorial.proto_metadata.checksum)
}
#endif
inline void proto_metadata::set_checksum(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tutorial.proto_metadata.checksum)
}
inline void proto_metadata::set_checksum(const char* value, size_t size) {
  
  checksum_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tutorial.proto_metadata.checksum)
}
inline ::std::string* proto_metadata::mutable_checksum() {
  
  // @@protoc_insertion_point(field_mutable:tutorial.proto_metadata.checksum)
  return checksum_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* proto_metadata::release_checksum() {
  // @@protoc_insertion_point(field_release:tutorial.proto_metadata.checksum)
  
  return checksum_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void proto_metadata::set_allocated_checksum(::std::string* checksum) {
  if (checksum != nullptr) {
    
  } else {
    
  }
  checksum_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), checksum);
  // @@protoc_insertion_point(field_set_allocated:tutorial.proto_metadata.checksum)
}

// -------------------------------------------------------------------

// proto_general

// .tutorial.proto_metadata meta = 1;
inline bool proto_general::has_meta() const {
  return this != internal_default_instance() && meta_ != nullptr;
}
inline void proto_general::clear_meta() {
  if (GetArenaNoVirtual() == nullptr && meta_ != nullptr) {
    delete meta_;
  }
  meta_ = nullptr;
}
inline const ::tutorial::proto_metadata& proto_general::meta() const {
  const ::tutorial::proto_metadata* p = meta_;
  // @@protoc_insertion_point(field_get:tutorial.proto_general.meta)
  return p != nullptr ? *p : *reinterpret_cast<const ::tutorial::proto_metadata*>(
      &::tutorial::_proto_metadata_default_instance_);
}
inline ::tutorial::proto_metadata* proto_general::release_meta() {
  // @@protoc_insertion_point(field_release:tutorial.proto_general.meta)
  
  ::tutorial::proto_metadata* temp = meta_;
  meta_ = nullptr;
  return temp;
}
inline ::tutorial::proto_metadata* proto_general::mutable_meta() {
  
  if (meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::tutorial::proto_metadata>(GetArenaNoVirtual());
    meta_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tutorial.proto_general.meta)
  return meta_;
}
inline void proto_general::set_allocated_meta(::tutorial::proto_metadata* meta) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete meta_;
  }
  if (meta) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      meta = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:tutorial.proto_general.meta)
}

// bool compressed = 2;
inline void proto_general::clear_compressed() {
  compressed_ = false;
}
inline bool proto_general::compressed() const {
  // @@protoc_insertion_point(field_get:tutorial.proto_general.compressed)
  return compressed_;
}
inline void proto_general::set_compressed(bool value) {
  
  compressed_ = value;
  // @@protoc_insertion_point(field_set:tutorial.proto_general.compressed)
}

// .google.protobuf.Any msg = 10;
inline bool proto_general::has_msg() const {
  return this != internal_default_instance() && msg_ != nullptr;
}
inline const ::google::protobuf::Any& proto_general::msg() const {
  const ::google::protobuf::Any* p = msg_;
  // @@protoc_insertion_point(field_get:tutorial.proto_general.msg)
  return p != nullptr ? *p : *reinterpret_cast<const ::google::protobuf::Any*>(
      &::google::protobuf::_Any_default_instance_);
}
inline ::google::protobuf::Any* proto_general::release_msg() {
  // @@protoc_insertion_point(field_release:tutorial.proto_general.msg)
  
  ::google::protobuf::Any* temp = msg_;
  msg_ = nullptr;
  return temp;
}
inline ::google::protobuf::Any* proto_general::mutable_msg() {
  
  if (msg_ == nullptr) {
    auto* p = CreateMaybeMessage<::google::protobuf::Any>(GetArenaNoVirtual());
    msg_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tutorial.proto_general.msg)
  return msg_;
}
inline void proto_general::set_allocated_msg(::google::protobuf::Any* msg) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(msg_);
  }
  if (msg) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      msg = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, msg, submessage_arena);
    }
    
  } else {
    
  }
  msg_ = msg;
  // @@protoc_insertion_point(field_set_allocated:tutorial.proto_general.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tutorial

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_protobuf_5fgeneral_2eproto
