# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_general.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf_general.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16protobuf_general.proto\x12\x08tutorial\x1a\x19google/protobuf/any.proto\"\x10\n\x0eproto_metadata\"n\n\rproto_general\x12&\n\x04meta\x18\x01 \x01(\x0b\x32\x18.tutorial.proto_metadata\x12\x12\n\ncompressed\x18\x02 \x01(\x08\x12!\n\x03msg\x18\n \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_PROTO_METADATA = _descriptor.Descriptor(
  name='proto_metadata',
  full_name='tutorial.proto_metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=79,
)


_PROTO_GENERAL = _descriptor.Descriptor(
  name='proto_general',
  full_name='tutorial.proto_general',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='tutorial.proto_general.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compressed', full_name='tutorial.proto_general.compressed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='tutorial.proto_general.msg', index=2,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=191,
)

_PROTO_GENERAL.fields_by_name['meta'].message_type = _PROTO_METADATA
_PROTO_GENERAL.fields_by_name['msg'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['proto_metadata'] = _PROTO_METADATA
DESCRIPTOR.message_types_by_name['proto_general'] = _PROTO_GENERAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

proto_metadata = _reflection.GeneratedProtocolMessageType('proto_metadata', (_message.Message,), dict(
  DESCRIPTOR = _PROTO_METADATA,
  __module__ = 'protobuf_general_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.proto_metadata)
  ))
_sym_db.RegisterMessage(proto_metadata)

proto_general = _reflection.GeneratedProtocolMessageType('proto_general', (_message.Message,), dict(
  DESCRIPTOR = _PROTO_GENERAL,
  __module__ = 'protobuf_general_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.proto_general)
  ))
_sym_db.RegisterMessage(proto_general)


# @@protoc_insertion_point(module_scope)
